# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CNzOyD_R2AvXTruQ1hGOxRy03MQBq-C8

**Aula 2 importação**

importar a bibliote panda e definir uma nomeclatura.
"""

import pandas as pd

"""definir uma variavel.

.read_"tipo de executavel"(caminho do arquivo, nome da pagina )

variavel+ação da variavel.

.head() = pega o intevaldo de linhas que deve ser monstrado sem ele mostra a tabela de forma resumida.
"""

df_principal = pd.read_excel('/content/Aula 2 de Imersão Python - Tabela de ações.xlsx',sheet_name='Principal')
df_principal.head(10)

df_Total_de_acoes = pd.read_excel('/content/Aula 2 de Imersão Python - Tabela de ações.xlsx',sheet_name='Total_de_acoes')
df_Total_de_acoes.head(10)

df_Ticker = pd.read_excel('/content/Aula 2 de Imersão Python - Tabela de ações.xlsx',sheet_name='Ticker')
df_Ticker.head(10)

df_Chat_GPT = pd.read_excel('/content/Aula 2 de Imersão Python - Tabela de ações.xlsx',sheet_name='Chat_GPT')
df_Chat_GPT.head(10)